### ISSUE TITLE
Markdown list 

### ISSUE THREAD

**Issue by louisdecharson** [haghish/MarkDoc#13]
Hi,

I want to create a unnumbered list using standard markdown syntax
```
* item 1 
* item 2
- item 3
- item 4
```
But none of symbol `*` or `-` is working.
Should I do something special ?
Best and thanks for your time 
Louis

**Comment by haghish** [comment]
Provide an example and detailed information. The list notation for both numbered and unnumbered is supported by MarkDoc.

**Comment by louisdecharson** [comment]
Ok the error is mine. I was not doubling line breaks. Sorry about this and thanks for your time.

**Comment by haghish** [comment]
Please post your questions on Statalist unless you are sure you have found a bug.
