### ISSUE TITLE
markdoc inserts space in longer lines

### ISSUE THREAD

**Issue by benzipperer** [haghish/markdoc#14]
Try the following code

```
capture log close
qui log using test, replace
/***
This is a really long line that gets modified after running markdoc on the log file, at column 90.
***/
qui log close
markdoc test, export(md) replace
```

Then test.md will look like

```
This is a really long line that gets modified after running markdoc on
the log file, at c olumn 90.
```

**Comment by haghish** [comment]
sadly, it doesn't produce your error. Stata 14.2, markdoc 3.9.5, windows 7.

**Comment by benzipperer** [comment]
Thanks! You're right, I was using an older version. I installed 3.9.5 using your github stata module and the error disappeared.

Thanks again for the great packages!

**Comment by haghish** [comment]
I  "highly" recommend you to "watch" the package updates if you plan to use it often. 80% of bug reports are due to using old versions... it'd save time to both of us ;)
