### ISSUE TITLE
Line Endings

### ISSUE THREAD

**Issue by chris-prener** [haghish/markdoc#16]
Hi @haghish,
Thanks for the fix on r(132) - it does seem to be working. However, the latest version on GitHub has a new bug - it is placing `\` characters at the end of lines and inserting line breaks into blocks of Markdown formatted text.

I've uploaded a text file generated with the `tooFewQuotes.do` file I sent on my previous issue - no change to the code was made. The only change was pulling down the latest version of MarkDoc from GitHub.

Thanks for checking this issue out! I really appreciate the quick response - a new batch of students will be installing Markdoc on Monday at the beginning of the new semester here in the U.S.

cheers,
@chris-prener

[tooFewQuotesSlash.txt](https://github.com/haghish/markdoc/files/705360/tooFewQuotesSlash.txt)

**Comment by haghish** [comment]
right. then I have to look into that in more details. I reverted the changes I made, so the previous bug remains. You could open an issue again and add what I mentioned. I hope I find the time to fix it. For now, just avoid the "`" to be the last character...
