### ISSUE TITLE
r(132): Too Many Quotes

### ISSUE THREAD

**Issue by chris-prener** [haghish/markdoc#17]
Hi @haghish,
Following up on your comment last night. 

The [original issue](https://github.com/haghish/markdoc/issues/15) described an error that occurs involving the single backtick in Markdown used to identify, for example, a variable name or a file path:

```
# Open `auto.dta`
The variable `mpg` is the variable that everyone uses.
```

When I use those backticks in my do-files, I routinely get error r(132): Too Few Quotes. Your [initial fix](https://github.com/haghish/markdoc/issues/15) addressed a bug that was causing MarkDoc to crash when a backtick appeared at the end of the line. 

However, the fix for the bug created [an issue](https://github.com/haghish/markdoc/issues/16) where MarkDoc placing `\` characters at the end of lines and inserting line breaks into blocks of Markdown formatted text.

I really appreciate you continuing to look for a solution that will allow for backticks to be used throughout MarkDoc do-files!

cheers,
@chris-prener

**Comment by haghish** [comment]
thanks. But basically you confirm that the bug is avoidable if the "`" is not the last character of a text line?

**Comment by chris-prener** [comment]
that does seem to be the case right now, yes.

**Comment by haghish** [comment]
I remember I had tried to fix this issue but I couldn't, for a particular bug I was getting in Stata 14. Haven't tried it with Stata 15... bug fix suggestions are welcome

**Comment by haghish** [comment]
The bug is fixed now, thanks for the bug report.
