### ISSUE TITLE
[version 3.9.6] HTML markup option is not working

### ISSUE THREAD

**Issue by coqauvin** [haghish/markdoc#20]
Hello,

When using the latest version of Markdoc (3.9.6), and when trying to save an HTML document, the markup option does not work, particularly for printing out the output of a command (summarize for instance) and for printing out graphs.

The following code is an example of this issue:

`qui log using example, replace

//OFF
sysuse auto, clear
histogram price
//ON

/**/ img

/**/ sum price

qui log c
markdoc example, markup(html) export(html) replace`

When reverting back to the latest version of Markdoc available on SSC (3.6.9), the code above works perfectly.

Thanks,
Emmanuel

**Comment by haghish** [comment]
your code is false. you specify the markup(html) ONLY when you have written the document using HTML codes.
