### ISSUE TITLE
Update to pandoc 2.0

### ISSUE THREAD

**Issue by anddis** [haghish/markdoc#23]
`--reference-docx` is no longer supported

This message is issued by `pandoc`:

    --smart/-S has been removed.  Use +smart or -smart extension instead.
    For example: pandoc -f markdown+smart -t markdown-smart.

**Comment by haghish** [comment]
That's bad! I have made several downloadble pandoc versions for Mac, Windows (32 and 64) and linux (32 & 64) and updating to pandoc 2.0 means updating all of these files. 

I will keep this in mind for the future "big release" if markdoc still will be useful by next year. 

Cheers mate,
