### ISSUE TITLE
Windows: loading images into PDFs

### ISSUE THREAD

**Issue by kaiemjoy** [haghish/markdoc#25]
In Stata version 15 on Windows - MakDoc fails to load files/images when compiling PDFs. 

It works when compiling a docX or when operating Stata 15 on a Mac. 

The error reads from the command pop-up:
"Loading pages <1/6>
Warning: Failed to load file::///C:filepath.graph.png 
<ignore>. "

**Comment by haghish** [comment]
Thank you for this bug report. It will be fixed in the next release (version 4.0.0)
