### ISSUE TITLE
Changing accent to {c 96}

### ISSUE THREAD

**Issue by matias-fresard** [haghish/markdoc#32]
I have been trying to create a Markdoc file from a Do file using State, but inside the Do file I have several loops using \`var' local variables and for no clear reason to me, the markdoc command changes \` to {c 96}, and not found a way to prevent this from happening.

I would really appreciate your help on this.

**Comment by haghish** [comment]
hi matias, Stata - until version 15 - was not handling the accents well, confusing them as macros during text processing. Actually, this limitation made me do some nasty work-arounds and I'm really hesitated to get into it again... This is not a markdoc limitation, instead, Stata's... Translating the accents to ASCII helped me get around it at the time of developping markdoc but I am not so sure if Stata 17 solves this issue.
