### ISSUE TITLE
Creating tables from outreg or estout output?

### ISSUE THREAD

**Issue by garretchristensen** [haghish/MarkDoc#7]
Is there a way to easily include a table generated after a regression in Markdoc output?  I see the tbl command in weaver, but it would be really nice to just be able to generate a full regression output table using outreg2 or estout (as text or LaTeX or whatever) and then just include that output file in the Markdoc output, as one can do with a figure.

**Comment by haghish** [comment]
Hi Garret

It is. you can just import the latex file or merge the html. some questions were already answered about that on stata-forum. 

see the new help file of markdoc as well
