### ISSUE TITLE
Using a dataset as a table with tbl

### ISSUE THREAD

**Issue by aghaynes** [haghish/MarkDoc#9]
Hi,

Is it possible to use an entire dataset as a table with tbl? I've looked through the help files and have the impression that the only way to create is to use a long string of macros/scalars etc. I often use post files to store results and it would be great to just pull those into the document without having to generate lots of macros...

Thanks

Alan

**Comment by haghish** [comment]
There is a smarter way to do that. There are other packages that can EXPORT LaTeX, HTML, or Markdown tables. 

Based on the markup language you are writing with, you can use the __`//IMPORT filename`__ to import the exported table in your document. See the help file.

**Comment by aghaynes** [comment]
Hi haghish, 

Could you make a couple of suggestions? Tracking down the relevant packages is proving difficult. It might also make a good addition to your help files...

Thanks

Alan

**Comment by haghish** [comment]
If you post on [Statalist.org](http://www.statalist.org/forums/) I will surely do that. These questions are rather common and I am afraid, only the developers end up on my GitHub.
